package com.pointlion.sys.mvc.common.model;

import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.model.base.BaseSysDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDept extends BaseSysDept<SysDept> {
	public static final SysDept dao = new SysDept();
	/***
	 * 根据主键查询
	 */
	public SysDept getById(String id){
		return SysDept.dao.findById(id);
	}
	/***
	 * 查询部门分页
	 * @param curr
	 * @param pagesize
	 * @return
	 */
	public Page<Record> getDeptPage(Integer curr , Integer pagesize){
		//return SysDept.dao.paginate(curr, pagesize, "select * ", " from sys_dept");

		return Db.paginate(curr, pagesize, "select * ", " from sys_dept");
	}
	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
		String idarr[] = ids.split(",");
		for(String deptid : idarr){
			SysDept menu = SysDept.dao.getById(deptid);
			if(menu!=null){
				menu.delete();//删除部门
			}
			//return Db.update("delete from sys_user_role  where user_id='"+userid+"'");

		}
	}
}
